### PR TITLE
Make cli bundler more robust to unpacking failure

### LINKED ISSUE #84: Nondeterministic failures due to missing compiler file
Occasionally, the plugin with a failure like the below:
```
./godelw conjure
Error: failed to execute [/var/folders/hm/pb6ft_vs5r1604m2z_z1z5ld0808zm/T/_conjureircli/conjure-4.6.1/bin/conjure compile ./conjure/defs /var/folders/hm/pb6ft_vs5r1604m2z_z1z5ld0808zm/T/466488667/out.json]
Output:
: fork/exec /var/folders/hm/pb6ft_vs5r1604m2z_z1z5ld0808zm/T/_conjureircli/conjure-4.6.1/bin/conjure: no such file or directory
```
This can be resolved by deleting the temp directory so we can try again. We don't know why this happens, but we could be more defensive to it.

### PR DESCRIPTION
**Pull request by bmoylan**
## Before this PR
We've seen failures unpacking the conjure binary (fixes #84) 

## After this PR

==COMMIT_MSG==
Make cli bundler more robust to unpacking failure
==COMMIT_MSG==

## Possible downsides?

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/godel-conjure-plugin/85)

### CODE REVIEW

File: ir-gen-cli-bundler/conjureircli/run.go [hunk 1]
```diff
@@ -73,37 +73,57 @@ func Run(inPath, outPath string) error {
...
 	if err != nil {
 		return errors.WithStack(err)
 	}
-	return errors.WithStack(archiver.TarGz.Read(bytes.NewReader(tgzBytes), path.Dir(dstPath)))
+	if err := archiver.TarGz.Read(bytes.NewReader(tgzBytes), cliUnpackDir()); err != nil {
+		return errors.WithStack(err)
+	}
+
+	// check that we can now find the cli
+	if _, err := os.Stat(cliPath); err != nil {
```
Comment (tabboud) [inline ir-gen-cli-bundler/conjureircli/run.go:124]: How about pulling line 104 into a function as well and calling that here so we have consistent checks for the `cliPath` existing?

File: ir-gen-cli-bundler/conjureircli/run.go [hunk 2]
```diff
@@ -73,37 +73,57 @@ func Run(inPath, outPath string) error {
...
 
-func ensureCLIExists(dstPath string) error {
-	if fi, err := os.Stat(dstPath); err == nil && fi.IsDir() {
+func ensureCLIExists(cliPath string) error {
+	if fi, err := os.Stat(cliPath); err == nil && fi.Mode().IsRegular() && fi.Size() > 0 {
 		// destination already exists
 		return nil
 	}
 
+	// destination does not exist or is malformed, remove the dest dir just in case of a previous bad install
```
Comment (tabboud) [inline ir-gen-cli-bundler/conjureircli/run.go:109]: There is mismatched naming here and below between `destination dir` and `archive dir`

File: ir-gen-cli-bundler/conjureircli/run.go [hunk 3]
```diff
@@ -73,37 +73,57 @@ func Run(inPath, outPath string) error {
...
+		return errors.Wrap(err, "failed to remove destination dir before unpacking cli archive")
+	}
+
 	// expand asset into destination
 	tgzBytes, err := conjureircli_internal.Asset("conjure.tgz")
 	if err != nil {
 		return errors.WithStack(err)
 	}
-	return errors.WithStack(archiver.TarGz.Read(bytes.NewReader(tgzBytes), path.Dir(dstPath)))
+	if err := archiver.TarGz.Read(bytes.NewReader(tgzBytes), cliUnpackDir()); err != nil {
```
Comment (tabboud) [inline ir-gen-cli-bundler/conjureircli/run.go:119]: Are we guaranteed that this `cliUnpackDir` will exist or do we need to create that upfront as well?

File: ir-gen-cli-bundler/conjureircli/run.go (hunk 1 above)
Comment (bmoylan) [reply ir-gen-cli-bundler/conjureircli/run.go]: done

File: ir-gen-cli-bundler/conjureircli/run.go (hunk 2 above)
Comment (bmoylan) [reply ir-gen-cli-bundler/conjureircli/run.go]: fixed! Also added some comments to each directory so it's obvious what they are

File: ir-gen-cli-bundler/conjureircli/run.go (hunk 3 above)
Comment (bmoylan) [reply ir-gen-cli-bundler/conjureircli/run.go]: The tar reader does a `os.MkdirAll` when unpacking so it doesn't need to exist ahead of time
